<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProvincesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        DB::table('provinces')->delete();

        DB::table('provinces')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Ilocos Norte',
                'region_code' => '1',
                'code' => '1',
                'order' => 11,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'Ilocos Sur',
                'region_code' => '1',
                'code' => '2',
                'order' => 12,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'La Union',
                'region_code' => '1',
                'code' => '3',
                'order' => 13,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'Pangasinan',
                'region_code' => '1',
                'code' => '4',
                'order' => 14,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'Batanes',
                'region_code' => '2',
                'code' => '5',
                'order' => 15,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'name' => 'Cagayan',
                'region_code' => '2',
                'code' => '6',
                'order' => 16,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'name' => 'Isabela',
                'region_code' => '2',
                'code' => '7',
                'order' => 17,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'name' => 'Nueva Vizcaya',
                'region_code' => '2',
                'code' => '8',
                'order' => 18,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'name' => 'Quirino',
                'region_code' => '2',
                'code' => '9',
                'order' => 19,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'name' => 'Bataan',
                'region_code' => '3',
                'code' => '10',
                'order' => 21,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'name' => 'Bulacan',
                'region_code' => '3',
                'code' => '11',
                'order' => 22,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'name' => 'Nueva Ecija',
                'region_code' => '3',
                'code' => '12',
                'order' => 23,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'name' => 'Pampanga',
                'region_code' => '3',
                'code' => '13',
                'order' => 24,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'name' => 'Tarlac',
                'region_code' => '3',
                'code' => '14',
                'order' => 25,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'name' => 'Zambales',
                'region_code' => '3',
                'code' => '15',
                'order' => 26,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'name' => 'Aurora',
                'region_code' => '3',
                'code' => '16',
                'order' => 20,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'name' => 'Batangas',
                'region_code' => '40',
                'code' => '17',
                'order' => 27,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'name' => 'Cavite',
                'region_code' => '40',
                'code' => '18',
                'order' => 28,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'name' => 'Laguna',
                'region_code' => '40',
                'code' => '19',
                'order' => 29,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'name' => 'Quezon',
                'region_code' => '40',
                'code' => '20',
                'order' => 30,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'name' => 'Rizal',
                'region_code' => '40',
                'code' => '21',
                'order' => 31,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 =>
            array (
                'id' => 22,
                'name' => 'Albay',
                'region_code' => '5',
                'code' => '22',
                'order' => 37,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 =>
            array (
                'id' => 23,
                'name' => 'Camarines Norte',
                'region_code' => '5',
                'code' => '23',
                'order' => 38,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'name' => 'Camarines Sur',
                'region_code' => '5',
                'code' => '24',
                'order' => 39,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 =>
            array (
                'id' => 25,
                'name' => 'Catanduanes',
                'region_code' => '5',
                'code' => '25',
                'order' => 40,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 =>
            array (
                'id' => 26,
                'name' => 'Masbate',
                'region_code' => '5',
                'code' => '26',
                'order' => 41,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 =>
            array (
                'id' => 27,
                'name' => 'Sorsogon',
                'region_code' => '5',
                'code' => '27',
                'order' => 42,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 =>
            array (
                'id' => 28,
                'name' => 'Aklan',
                'region_code' => '6',
                'code' => '28',
                'order' => 43,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 =>
            array (
                'id' => 29,
                'name' => 'Antique',
                'region_code' => '6',
                'code' => '29',
                'order' => 44,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'name' => 'Capiz',
                'region_code' => '6',
                'code' => '30',
                'order' => 45,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 =>
            array (
                'id' => 31,
                'name' => 'Iloilo',
                'region_code' => '6',
                'code' => '31',
                'order' => 46,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 =>
            array (
                'id' => 32,
                'name' => 'Negros Occidental',
                'region_code' => '6',
                'code' => '32',
                'order' => 47,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-08-07 09:19:50',
            ),
            32 =>
            array (
                'id' => 33,
                'name' => 'Guimaras',
                'region_code' => '6',
                'code' => '33',
                'order' => 48,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 =>
            array (
                'id' => 34,
                'name' => 'Bohol',
                'region_code' => '7',
                'code' => '34',
                'order' => 49,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 =>
            array (
                'id' => 35,
                'name' => 'Cebu',
                'region_code' => '7',
                'code' => '35',
                'order' => 50,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 =>
            array (
                'id' => 36,
                'name' => 'Negros Oriental',
                'region_code' => '7',
                'code' => '36',
                'order' => 51,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-08-07 09:20:08',
            ),
            36 =>
            array (
                'id' => 37,
                'name' => 'Siquijor',
                'region_code' => '7',
                'code' => '37',
                'order' => 52,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-08-07 09:19:24',
            ),
            37 =>
            array (
                'id' => 38,
                'name' => 'Eastern Samar',
                'region_code' => '8',
                'code' => '38',
                'order' => 54,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 =>
            array (
                'id' => 39,
                'name' => 'Leyte',
                'region_code' => '8',
                'code' => '39',
                'order' => 55,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 =>
            array (
                'id' => 40,
                'name' => 'Northern Samar',
                'region_code' => '8',
                'code' => '40',
                'order' => 56,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 =>
            array (
                'id' => 41,
                'name' => 'Samar',
                'region_code' => '8',
                'code' => '41',
                'order' => 57,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 =>
            array (
                'id' => 42,
                'name' => 'Southern Leyte',
                'region_code' => '8',
                'code' => '42',
                'order' => 58,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 =>
            array (
                'id' => 43,
                'name' => 'Biliran',
                'region_code' => '8',
                'code' => '43',
                'order' => 53,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 =>
            array (
                'id' => 44,
                'name' => 'Zamboanga del Norte',
                'region_code' => '9',
                'code' => '44',
                'order' => 59,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 =>
            array (
                'id' => 45,
                'name' => 'Zamboanga del Sur',
                'region_code' => '9',
                'code' => '45',
                'order' => 60,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 =>
            array (
                'id' => 46,
                'name' => 'Zamboanga Sibugay',
                'region_code' => '9',
                'code' => '46',
                'order' => 61,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 =>
            array (
                'id' => 47,
                'name' => 'Bukidnon',
                'region_code' => '10',
                'code' => '47',
                'order' => 62,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 =>
            array (
                'id' => 48,
                'name' => 'Camiguin',
                'region_code' => '10',
                'code' => '48',
                'order' => 63,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 =>
            array (
                'id' => 49,
                'name' => 'Lanao del Norte',
                'region_code' => '10',
                'code' => '49',
                'order' => 64,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 =>
            array (
                'id' => 50,
                'name' => 'Misamis Occidental',
                'region_code' => '10',
                'code' => '50',
                'order' => 65,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 =>
            array (
                'id' => 51,
                'name' => 'Misamis Oriental',
                'region_code' => '10',
                'code' => '51',
                'order' => 66,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 =>
            array (
                'id' => 52,
                'name' => 'Davao del Norte',
                'region_code' => '11',
                'code' => '52',
                'order' => 69,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 =>
            array (
                'id' => 53,
                'name' => 'Davao del Sur',
                'region_code' => '11',
                'code' => '53',
                'order' => 70,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 =>
            array (
                'id' => 54,
                'name' => 'Davao Oriental',
                'region_code' => '11',
                'code' => '54',
                'order' => 71,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 =>
            array (
                'id' => 55,
            'name' => 'Davao de Oro (formerly Compostela Valley)',
                'region_code' => '11',
                'code' => '55',
                'order' => 68,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 =>
            array (
                'id' => 56,
                'name' => 'Davao Occidental',
                'region_code' => '11',
                'code' => '56',
                'order' => 72,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 =>
            array (
                'id' => 57,
            'name' => 'Cotabato (North Cotabato)',
                'region_code' => '12',
                'code' => '57',
                'order' => 73,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 =>
            array (
                'id' => 58,
                'name' => 'South Cotabato',
                'region_code' => '12',
                'code' => '58',
                'order' => 75,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 =>
            array (
                'id' => 59,
                'name' => 'Sultan Kudarat',
                'region_code' => '12',
                'code' => '59',
                'order' => 76,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 =>
            array (
                'id' => 60,
                'name' => 'Sarangani',
                'region_code' => '12',
                'code' => '60',
                'order' => 74,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 =>
            array (
                'id' => 61,
                'name' => 'Metro Manila',
                'region_code' => '16',
                'code' => '61',
                'order' => 0,
                'lgu_type' => 'P',
                'status' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 =>
            array (
                'id' => 62,
                'name' => 'Abra',
                'region_code' => '15',
                'code' => '62',
                'order' => 5,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 =>
            array (
                'id' => 63,
                'name' => 'Apayao',
                'region_code' => '15',
                'code' => '63',
                'order' => 6,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 =>
            array (
                'id' => 64,
                'name' => 'Benguet',
                'region_code' => '15',
                'code' => '64',
                'order' => 7,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 =>
            array (
                'id' => 65,
                'name' => 'Ifugao',
                'region_code' => '15',
                'code' => '65',
                'order' => 8,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 =>
            array (
                'id' => 66,
                'name' => 'Kalinga',
                'region_code' => '15',
                'code' => '66',
                'order' => 9,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 =>
            array (
                'id' => 67,
                'name' => 'Mountain Province',
                'region_code' => '15',
                'code' => '67',
                'order' => 10,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 =>
            array (
                'id' => 68,
                'name' => 'Agusan del Norte',
                'region_code' => '13',
                'code' => '68',
                'order' => 77,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 =>
            array (
                'id' => 69,
                'name' => 'Agusan del Sur',
                'region_code' => '13',
                'code' => '69',
                'order' => 78,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 =>
            array (
                'id' => 70,
                'name' => 'Dinagat Islands',
                'region_code' => '13',
                'code' => '70',
                'order' => 79,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 =>
            array (
                'id' => 71,
                'name' => 'Surigao del Norte',
                'region_code' => '13',
                'code' => '71',
                'order' => 80,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 =>
            array (
                'id' => 72,
                'name' => 'Surigao del Sur',
                'region_code' => '13',
                'code' => '72',
                'order' => 81,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 =>
            array (
                'id' => 73,
                'name' => 'Basilan',
                'region_code' => '14',
                'code' => '73',
                'order' => 83,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 =>
            array (
                'id' => 74,
                'name' => 'Lanao del Sur',
                'region_code' => '14',
                'code' => '74',
                'order' => 84,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 =>
            array (
                'id' => 75,
                'name' => 'Maguindanao',
                'region_code' => '14',
                'code' => '75',
                'order' => 85,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 =>
            array (
                'id' => 76,
                'name' => 'Sulu',
                'region_code' => '14',
                'code' => '76',
                'order' => 86,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 =>
            array (
                'id' => 77,
                'name' => 'Tawi-Tawi',
                'region_code' => '14',
                'code' => '77',
                'order' => 87,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 =>
            array (
                'id' => 78,
                'name' => 'Marinduque',
                'region_code' => '41',
                'code' => '78',
                'order' => 32,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 =>
            array (
                'id' => 79,
                'name' => 'Occidental Mindoro',
                'region_code' => '41',
                'code' => '79',
                'order' => 33,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 =>
            array (
                'id' => 80,
                'name' => 'Oriental Mindoro',
                'region_code' => '41',
                'code' => '80',
                'order' => 34,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 =>
            array (
                'id' => 81,
                'name' => 'Palawan',
                'region_code' => '41',
                'code' => '81',
                'order' => 35,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 =>
            array (
                'id' => 82,
                'name' => 'Romblon',
                'region_code' => '41',
                'code' => '82',
                'order' => 36,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 =>
            array (
                'id' => 83,
            'name' => 'First District (Manila)',
                'region_code' => '16',
                'code' => '83',
                'order' => 1,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 =>
            array (
                'id' => 84,
            'name' => 'Second District (Mandaluyong, Marikina, Pasig, Quezon City, San Juan)',
                'region_code' => '16',
                'code' => '84',
                'order' => 2,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 =>
            array (
                'id' => 85,
            'name' => 'Third District (Caloocan, Malabon, Navotas, Valenzuela)',
                'region_code' => '16',
                'code' => '85',
                'order' => 3,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 =>
            array (
                'id' => 86,
            'name' => 'Fourth District (Las Piñas, Makati, Muntinlupa, Parañaque, Pasay, Pateros, Taguig)',
                'region_code' => '16',
                'code' => '86',
                'order' => 4,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 =>
            array (
                'id' => 87,
                'name' => 'Cagayan de Oro',
                'region_code' => '10',
                'code' => '87',
                'order' => 67,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 =>
            array (
                'id' => 88,
                'name' => 'Butuan',
                'region_code' => '13',
                'code' => '88',
                'order' => 82,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 =>
            array (
                'id' => 89,
            'name' => 'Negros Occidental (NIR)',
                'region_code' => '42',
                'code' => '89',
                'order' => 89,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => '2025-08-07 09:21:15',
                'updated_at' => '2025-08-07 09:21:15',
            ),
            89 =>
            array (
                'id' => 90,
            'name' => 'Negros Oriental (NIR)',
                'region_code' => '42',
                'code' => '90',
                'order' => 90,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => '2025-08-07 09:22:46',
                'updated_at' => '2025-08-07 09:22:46',
            ),
            90 =>
            array (
                'id' => 91,
            'name' => 'Siquijor (NIR)',
                'region_code' => '42',
                'code' => '91',
                'order' => 91,
                'lgu_type' => 'P',
                'status' => 1,
                'created_at' => '2025-08-07 09:23:01',
                'updated_at' => '2025-08-07 09:23:01',
            ),
        ));


    }
}
